
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 22 11:19:59 CEST 2015
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 15;
  public static final int LT = 24;
  public static final int NE = 23;
  public static final int IDENT = 31;
  public static final int ASGN = 11;
  public static final int ELSE = 4;
  public static final int PLUS = 18;
  public static final int RPAREN = 13;
  public static final int LCURL = 16;
  public static final int WHILE = 10;
  public static final int SLASH = 21;
  public static final int STAR = 20;
  public static final int LBRACK = 14;
  public static final int REF = 8;
  public static final int IF = 3;
  public static final int COLON = 28;
  public static final int GT = 26;
  public static final int LPAREN = 12;
  public static final int LE = 25;
  public static final int OF = 6;
  public static final int INTLIT = 32;
  public static final int SEMIC = 30;
  public static final int TYPE = 5;
  public static final int COMMA = 29;
  public static final int EOF = 0;
  public static final int GE = 27;
  public static final int MINUS = 19;
  public static final int error = 1;
  public static final int PROC = 7;
  public static final int EQ = 22;
  public static final int RCURL = 17;
  public static final int ARRAY = 2;
  public static final int VAR = 9;
}

